on:
  release:
    types: [published]
jobs:
  build_and_deploy_web_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
          VITE_WC_PROJECT_ID: "${{ secrets.WC_PROJECT_ID }}"
          VITE_RESCUE_API_BASE_URL: "${{ secrets.RESCUE_API_BASE_URL }}"
      # TODO: publish `dist/` to production
